### ISSUE TITLE
If single test step fails, testcase should be aborted

### ISSUE THREAD

**Issue by sshedmake** [wtrobot/wtrobot-v2#3]
**Description**
If single test step fails, testcase should be aborted

**Actual Results**
gets Traceback and execute next step

**Expected Results**
should abort / exit entire testcase

**Comment by vishalvvr** [comment]
Fixed in [commit](https://github.com/vishalvijayraghavan/WTRobot-v2/commit/fc067b08d147fb72befee2d0afb7fe649c9fb5aa)
