### ISSUE TITLE
[RFE] Screenshot of some tool-tips (with the required screen) are missed

### ISSUE THREAD

**Issue by sshedmake** [wtrobot/wtrobot-v2#5]
**Description**
Co-incidentally, screenshot_name of some tool-tips (with the required screen) are missed

**Steps to Reproduce**
1. In test script file, use, 'screenshot_name: test-1-2-3'
2. Sleep for required seconds before the action (say - click / hover) actually happens

**Actual Results**
Screenshot (with screenshot_name) exists, with after / before, the exact (or required) screen

**Expected Results**
screenshot (with screenshot_name ) exists with the exact (or required) screen

**Comment by vishalvvr** [comment]
Hi Sandeep,
So the thing is whenever you click some widget on your page it might change the dom i:e it will switch to some other page or the widget will change/update. Depending on network this change might be slow or fast to be captured in screenshot.

So tool tips on hover action can be captured in screenshot but with click action i am doubtful.  
Thanks for reporting will again look into it :)

**Comment by sshedmake** [comment]
Reported problem now looks fixed when:
- **hover, wait before action, wait after action** are used in combination in a step
- **click, wait after action** are used in combination in a step

**Comment by sshedmake** [comment]
Marking this issue as fixed.

Thanks.
